DROP TABLE IF EXISTS "posts";
CREATE TABLE "posts" ("id" integer primary key autoincrement not null, "created_at" datetime, "updated_at" datetime, "offer" varchar(255), "description" text, "validto" date, "validtonotes" text, "company" varchar(255), "phone" varchar(255), "email" varchar(255), "website" varchar(255), "facebook" varchar(255), "twitter" varchar(255), "address" text, "latitude" decimal, "longitude" decimal, "openingtimes" text, "metadata" text, "imgurl" varchar(255), "web" varchar(255), "nus" varchar(255));
INSERT INTO "posts" VALUES(1,'2010-10-25 15:04:06','2011-03-22 00:33:43','20% Off At PizzaExpress','Famed for bringing authentic pizza to the UK in back in 1965, PizzaExpress is the nation’s favourite high street pizza restaurant. From classic favourites like the American Hot and Margherita, to our thinner, crispier Romana pizzas and our lighter ‘Leggera’ options, NUS Extra cardholders can enjoy 20% off their total food bill. This offer is valid Sunday-Thursday.\r\n\r\nFor a list of restaurants please visit<a href="http://www.pizzaexpress.com/" target="_blank">www.pizzaexpress.com</a>\r\n\r\n<strong>Terms and conditions</strong>\r\n\r\n•The NUS Extra Card entitles you to a 20% discount off total food bill at PizzaExpress\r\n\r\n•Valid Sunday – Thursday until 28th July 2011\r\n\r\n•Offer applies to food items only and does not include drinks\r\n\r\n•Valid on takeaway and restaurant sales\r\n\r\n•The NUS Extra Card offer cannot be used in conjunction with any other offer, voucher or set menu\r\n\r\n•Valid at every PizzaExpress restaurant in the UK. Please visit <a href="http://www.pizzaexpress.com/" target="_blank">www.pizzaexpress.com</a> for a full list of locations','2011-07-28','Sunday – Thursday','PizzaExpress','(01483)300122','','http://www.pizzaexpress.com/','http://www.facebook.com/pizzaexpress','http://twitter.com/pizzaexpress','237-241 High Street,
Guildford,
Surrey,
GU1 3BJ. ',51.2375063,-0.56708,'Mon: 11:30 AM - 11:00 PM
Tue: 11:30 AM - 11:00 PM
Wed: 11:30 AM - 11:00 PM
Thu: 11:30 AM - 11:30 PM
Fri: 11:30 AM - 11:30 PM
Sat: 11:30 AM - 11:30 PM
Sun: 11:30 AM - 11:00 PM','food restaurant pizza express pizzaexpress','/images/companylogos/pizzaexpress1-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(2,'2010-10-25 15:14:40','2011-03-22 00:33:33','12.5% discount in Ryman','Exclusive 12.5% discount at Ryman with your NUS Extra card! Get discounts on a range of stationery products from folders and files to pens and pencils.\r\n\r\nRyman the stationers is delighted to offer a 12.5% discount on our fantastic range of over 4,000 products. See our range at <a href="http://www.ryman.co.uk/nusextra" target="_blank">www.ryman.co.uk/nusextra</a> - exclusively for NUS Extra cardholders.',NULL,'Valid until further notice.','Ryman','','','http://www.ryman.co.uk/nusextra','','','',51.2368419,-0.5688869,'','stationery','/images/companylogos/RymanLogo1-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(3,'2010-10-25 15:22:16','2011-03-22 00:33:22','25% off when you spend £25 or more at Dominos','Get an outstanding 25% OFF when you spend £25 or more online at<span style="text-decoration: underline;"><a href="http://www.dominos.co.uk/" target="_blank">www.dominos.co.uk</a>.</span>\r\n\r\n<strong>Working up an appetite?</strong>\r\n\r\nWith your NUS Extra card you can enjoy hot, fresh and delicious Domino’s pizza with 25% OFF whenever hunger strikes!\r\n\r\nWhat’s more, the next time your mum calls you can tell here there’s no need to worry as you’re eating well.\r\n\r\n<strong>Why?</strong>\r\n\r\nBecause only Domino’s pizza is made from the freshest ingredients cooked to perfection and served on your choice of hand-made dough base – so each and every slice delivers a meal your mum would be proud of.\r\n\r\nSo when mum calls, don’t lie – tell her you’ve been eating delicious Domino’s.

Enter this code in the vouchers box at checkout online, not valid in conjunction with other offers.
CODE: NUSEXTRA',NULL,'Valid until further notice.','Dominos','','','http://www.dominos.co.uk/','','','',51.2449193,-0.5768789,'','fast food pizza','/images/companylogos/dominos-150x150.jpg','1','1');
INSERT INTO "posts" VALUES(4,'2010-10-25 15:33:14','2011-03-22 00:32:51','Free Medium Fries with a Big Mac® or McChicken® Sandwich','Get Free Medium Fries with the purchase of a Big Mac® or McChicken® Sandwich.\r\n\r\nWhen you present your NUS Extra card.\r\n\r\n<strong>Terms and Conditions</strong>\r\n\r\nPresent your valid NUS Extra card before ordering to redeem the offer.\r\n\r\nServed after 10:30am at participating restaurants. Products on sale may be restricted at different times. Cannot be used in conjunction with any other offer. One offer per person, per card, per visit. Valid between 1st September 2010 - 31st August 2011. ©2010 McDonalds','2011-08-31','Valid between 1st September 2010 - 31st August 2011','McDonalds','','','','','','',51.2372187,-0.5679049,'','fast food restaurant','/images/companylogos/mcdonalds-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(5,'2010-10-25 15:39:44','2011-03-22 00:32:43','25% off cinema ticket','See great new films for less on Mondays – Thursdays with ODEON and NUS Extra; Save an additional 25% off the price of a student/teen ticket by showing your NUS Extra card at any participating ODEON.\r\n\r\nThe offer just gets better and better as now 3D films are included. So what are you waiting for? Simply print out the voucher and head down to your local ODEON with your valid NUS Extra card to start watching fantastic films for less.',NULL,'Valid until further notice.','Odeon','','','','','','',51.2384905,-0.578396,'','cinema movie film','/images/companylogos/Odeon-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(6,'2010-10-25 15:47:08','2011-03-22 00:32:35','10% off at JJB Sports','Attention all Students! If you are heavily involved with your Uni sports teams or you just prefer watching the match down at the Union…Don’t forget your 10% student discount at JJB Sports! Go online or visit one of over 250 stores nationwide.\r\n\r\nAs a fully fledged student we know that you are going to need anything and everything to get you started. As a result JJB Sports are offering all NUS Extra cardholders a 10% discount in store and online, this will allow you to get fully kitted out for University or College. Whether it be a new pair of trainers to hit the Union in, or a new gym outfit to start a health kick, JJB has all the top brands from Nike to adidas, Umbro to Reebok and many more.\r\n\r\nJJB Sports stocks a wide selection of sports, leisurewear, footwear and fitness equipment. If you prefer to keep fit in the comfort of your own home JJB Sports has all the cycles, rowers, treadmills and multi-gyms you need to keep you trim and toned. So you can either shop online at <a href="http://www.jjbsports.com/" target="_blank">www.jjbsports.com</a> or in one of over 250 stores nationwide.',NULL,'Valid until further notice.','JJB Sports','','','http://www.jjbsports.com/','','','',51.2362489,-0.5755066,'','','/images/companylogos/jjb-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(7,'2010-10-25 15:59:00','2011-03-22 00:32:26','£4 off on purchases of £45 at game.co.uk','Clever students save online at <a href="http://www.game.co.uk/nus/?cm_mmc=Partnerships-_-Voucher-_-NUSExtra-_-Link" target="_blank">GAME.co.uk</a>, the UK’s leading gaming specialist.\r\n\r\nVisit <a href="http://www.game.co.uk/nus/?cm_mmc=Partnerships-_-Voucher-_-NUSExtra-_-Link" target="_blank">GAME.co.uk</a> for the very latest exclusive student offers and to redeem your NUS Extra Card discounts.\r\n\r\n<strong>Terms and Conditions</strong> :\r\nVoucher valid from 05/08/2010 until 31/08/2011. Voucher only redeemable at Game.co.uk and not in any GAME Store. Minimum spend £45.\r\n\r\nThis promotion is only valid to NUS Extra Card members only and can not be redeemed via any cashback or point portals. Cannot be redeemed against gift vouchers, gift cards, preorder products, hardware, hardware inc Kinect and Move products and software bundles, GAME Rental, GAMEcare, GAME On Demand Download Service, GAME Download to own service, or mobile games.\r\n\r\nOrders not complying with these T''''s and C''''s will be cancelled by GAME Stores Group and no discussion entered into. Your email address will not be shared with any third parties. Cash value of the voucher is 0.001p. No alternative offered. GAME reserves the right to withdraw from this promotion at any time or cancel orders if the voucher is abused.','2011-08-31','from 05/08/2010 until 31/08/2011','Game','','','http://www.game.co.uk/nus/?cm_mmc=Partnerships-_-Voucher-_-NUSExtra-_-Link','','','',51.2358382,-0.5720834,'','video games online','/images/companylogos/game-150x150.jpg','1','1');
INSERT INTO "posts" VALUES(8,'2010-10-25 16:40:09','2011-03-22 00:31:49','Eye test for £5 and save 10% off when you spend £100 on glasses.','NUS Extra cardholders can get their eyes tested for only £5 AND save 10% when you spend £100 or more on a complete pair of glasses in any Boots Opticians and Dollond &amp; Aitchison practice nationwide.\r\n\r\nTo claim these discounts please print off the unique NUS Extra cardholder voucher and take to your appointment along with your NUS Extra card.\r\n\r\nTo book an appointment call <strong>0845 120 43 43.</strong>\r\n\r\nTo find your nearest Boots Opticians or D&amp;A practice, visit <a href="http://www.bootsopticians.com/" target="_blank">www.bootsopticians.com</a> or <a href="http://www.danda.co.uk/" target="_blank">www.danda.co.uk</a>.'', ''£5 Eye Test and save 10% when you spend £100 or more on a complete pair of glasses at Boots Opticians and Dollond & Aitchison',NULL,'Valid until further notice.','Boots','(08451)204343','','http://www.bootsopticians.com/','','','',51.2369822,-0.5684622,'','opticians','/images/companylogos/boots_logo-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(9,'2010-10-25 16:40:09','2011-03-22 00:32:11','Eye test for £5 and save 10% off when you spend £100 on glasses.','NUS Extra cardholders can get their eyes tested for only £5 AND save 10% when you spend £100 or more on a complete pair of glasses in any Boots Opticians and Dollond &amp; Aitchison practice nationwide.\r\n\r\nTo claim these discounts please print off the unique NUS Extra cardholder voucher and take to your appointment along with your NUS Extra card.\r\n\r\nTo book an appointment call <strong>0845 120 43 43.</strong>\r\n\r\nTo find your nearest Boots Opticians or D&amp;A practice, visit <a href="http://www.bootsopticians.com/" target="_blank">www.bootsopticians.com</a> or <a href="http://www.danda.co.uk/" target="_blank">www.danda.co.uk</a>.',NULL,'Valid until further notice.','Dollond & Aitchison','(01483)570093 ‎ ','','http://www.danda.co.uk/','','','94 High St, 
Guildford,
GU1 3HE.',51.235545,0.573203,'','opticians','/images/companylogos/DollandAitchison-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(10,'2010-11-02 10:40:44','2011-03-22 00:31:38','No Signing Up Fee At The Gym!','<span style="font-family: Arial, Helvetica, Geneva, sans-serif; line-height: 16px; font-size: 12px; color: #444117;"> </span>\r\n<h2 style="margin-top: 0px; margin-right: 0px; margin-bottom: 0.3em; margin-left: 0px; font-size: 1.3em; color: #5a5838; padding: 0px;"><span style="padding: 0px; margin: 0px;">Got an NUS Extra card? No joining fee for you then! A healthy lifestyle without bashing your bank balance.</span></h2>\r\nAt The Gym we understand the demands of student life. Lectures, tutorials, a social whirl you can barely keep up with and a student loan that a hermit would struggle to live on.  We’re here to help you achieve a healthy balance without bashing that fragile bank balance even further.\r\n\r\nAt The Gym there’s no joining fee, no contract, no obligation and no catch.\r\n\r\nWe did away with joining fees especially for you students – the start of semester is quite pricey enough as it is. Just enter your NUS Extra card number when you sign up.\r\n\r\nAnd we did away with contracts that tie you in, so if you find that money gets too tight, you can take a month or two off while you get your finances in order.\r\n\r\nBut at just £15.99 a month* we think The Gym is unbeatably affordable and tremendous value for money. Where else could you get a month’s access to premium fitness equipment, 24/7, for less than a night out at the student union bar?\r\n\r\nOpen 24/7. That’s right. Perfect for the student timetable. We remember pulling all-nighters to get essays and dissertations done on deadline. Which means you’re wide awake at 4am. Now you can keep your body active at any time of day or night as well as your mind.\r\n\r\n170+ premium fitness machines and free weights. Whether you’re a fitness fanatic, want to drop a dress size or just want to burn off the booze, we’ve got the right equipment for you. With so many machines available you can get on that treadmill without cooling your heels, or really mix up your workouts to keep your body guessing.\r\n\r\nHave we sold it to you yet?\r\n\r\nHave your NUS Extra card handy when you sign up, to make sure you benefit from the full student discount.\r\n\r\n* £15.99 a month where The Gym is already open. If you’re studying in a city where The Gym is soon to make an appearance you can sign up for £10.99 a month guaranteed for the first year. That’s less than getting a round in! So don’t waste time, sign up now.

NUS CARD REQUIRED',NULL,'Valid until further notice.','The Gym','','','','','','',51.2470831,-0.582492,'','gym','/images/companylogos/thegym-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(11,'2010-11-02 10:46:45','2011-03-22 00:31:25','20% off at Pizza Hut','Love Pizza? Pizza Hut loves students so we’re offering you 20% discount on the full menu price at Pizza Hut Delivery and Pizza Hut Restaurants.

NUS CARD REQUIRED',NULL,'Valid until further notice.','Pizza Hut','','','','','','',51.2362596,-0.5717592,'','fast food restaurant pizza','/images/companylogos/pizza-hut-logo-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(12,'2010-11-02 10:52:37','2011-05-05 00:26:06.375000','Save £250 on driving lessons!','Every 2 minutes someone passes with BSM*\r\n\r\nBSM is the UK’s number one driving school, with over 3000 instructors helping some 170,000 budding motorists to pass their test every year.\r\n\r\nWhile BSM is best known for teaching learner drivers, it also provides advanced driving training to individuals and businesses and is one of the largest providers of training for driving instructors. BSM also plays an active role in lobbying the Government on road safety and learner driver-related issues.\r\n\r\nAt BSM, pupils have always benefited from quality tuition from our instructors, who we train to the highest professional standards. Today, our learners also benefit from taking their lessons in one of our fleet of Fiat 500’s (Car of the Year 2008).\r\n\r\n15 Epsom Road\r\nGuildford, Surrey GU1 3JT\r\n01483 560 429

NUS CARD REQUIRED',NULL,'Valid until further notice.','BSM','(01483)560429','','','','','15 Epsom Road,
Guildford,
Surrey,
GU1 3JT',51.333,-0.467,'','driving instructor lessons test','/images/companylogos/BSM150x150.jpg','0','1');
INSERT INTO "posts" VALUES(13,'2010-11-02 10:58:06','2010-11-02 10:58:20','10% discount at La Senza','La Senza offers a wide selection of lingerie and nightwear in an array of colours and styles. With sizes ranging from 30A- 40GG your sure to find something to fit you perfectly.\r\n\r\nIf you are unsure of which bra to pick, expert advice is on hand and, with La Senza''''s free, professional bra fitting service, the perfect fit is guaranteed.

NUS CARD REQUIRED',NULL,'Valid until further notice.','La Senza',NULL,NULL,NULL,NULL,NULL,NULL,51.2351226,-0.574308,NULL,'lingerie nightwear','/images/companylogos/lasenzalogo-150x150.gif','0','1');
INSERT INTO "posts" VALUES(14,'2010-11-02 11:01:31','2011-03-22 00:30:52','15% off at Moss','With over 120 stores nationwide and styles to suit all tastes and budgets, you’ll find an extensive range of suits, shirts, casualwear and accessories. 

Present NUS card upon purchase.',NULL,'Valid until further notice.','Moss','','','','','','',51.2362738,-0.5702768,'','suits shirts ties','/images/companylogos/moss-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(15,'2010-11-02 11:05:28','2011-03-22 00:30:26','£100 free credit with Three','NUS Extra cardholders can get £100 bill credit from Three mobile totally free, after your third month, on one of their new great value phone plans\r\n\r\nThree are fast becoming champions of the mobile internet. And their aim is to help you go online whenever you like. That’s why they’re offering unlimited internet on all their mobile phone plans. So, you can enjoy loads more fun stuff, like Facebook™ and Windows Live™ Messenger, while you’re on the go.\r\n\r\nPlus, you even get Skype™ on Three. It’s completely free. So you can chat and message friends on Skype without eating up any of your plan’s minutes.\r\n\r\nCheck out the new deal on Three’s NUS Extra micro site. It’s updated regularly, so remember to come back and see what’s on offer.\r\n\r\nSubject to terms and conditions that can be found at<a href="http://www.3store.co.uk/" target="_blank">www.3store.co.uk</a>',NULL,'Valid until further notice','3 Mobile','','','http://www.3store.co.uk/','','','',51.2356394,-0.5724442,'','mobile phones','/images/companylogos/three_logo-150x150.png','0','1');
INSERT INTO "posts" VALUES(16,'2010-11-02 11:11:19','2011-03-22 00:30:12','10% off at Superdrug Stores','Britain''s most fashion conscious beauty and health retailer, committed to bringing innovation and the latest styles and trends to every high street in the UK at fantastic prices.

Just present NUS card upon purchase.',NULL,'Valid until further notice.','Superdrug','','','','','','',51.2357567,-0.5732141,'','medicine health','/images/companylogos/superdrug-logo-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(17,'2010-11-09 09:46:51','2011-04-18 22:10:42.421000','£25 for any tattoo','Electric Ink are offering any tattoo for £25 if you show an NUS card, and say the word TRIBAL when you ask for it!!! We would like to thank Lee of Electric Ink for giving us this fantastic offer!',NULL,'Valid until further notice.','Electric Ink','','','','','','',51.2382614,-0.5651754,'','tatoo','/images/companylogos/ElectricInk150x150.jpg','0','1');
INSERT INTO "posts" VALUES(18,'2010-11-09 09:49:34','2011-03-22 00:29:40','20% discount at Tony & Guy','Tony &amp; Guy Guildford are offering an amazing 20% discount on haircuts on a Monday, Tuesday or a Wednesday, when you show your NUS card!',NULL,'Valid until further notice.','Tony & Guy','','','','','','',51.2362809,-0.5688078,'','hairdresser barber hair cut ','/images/companylogos/TONI-GUY-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(19,'2010-11-09 09:52:34','2011-03-22 00:29:05','10% discount at Office Team Guildford!','Office Team Guildford is a stationary offering an amazing 10% discount to anyone with an NUS card! Go in today and stock up on your stationary supplies!',NULL,'Valid until further notice.','Office Team Guildford','','','','','','',51.2373987,-0.5721749,'','office stationary','/images/companylogos/OfficeTeam150x150.jpg','0','1');
INSERT INTO "posts" VALUES(20,'2010-11-09 09:57:23','2010-11-09 09:57:23','10% off at East West','East West is full of unique and amazing Eastern products. If you print this offer off and go into East West - you will save 10%. So get printing!',NULL,'Valid until further notice.','East West',NULL,NULL,NULL,NULL,NULL,NULL,51.2390677,-0.5733552,NULL,NULL,'/images/companylogos/East-West_250px-150x150.jpg','0','0');
INSERT INTO "posts" VALUES(21,'2010-11-09 10:00:35','2011-03-19 21:42:28','Buy 1 Get 1 Free at Mobile Master Guildford','Mobile Masters has all the mobile phone accessories you could wish for, and now we have a great offer to go with them! Buy 1 mobile phone case – and get another one (at the same price) for free. Print and bring a voucher with you.',NULL,'Valid until further notice.','Mobile Master Guildford','','','','','','',51.2371151,-0.5747335,'','mobile phones','/images/companylogos/MobileMaster-150x150.jpg','0','0');
INSERT INTO "posts" VALUES(22,'2010-11-09 10:03:31','2010-11-09 10:03:31','10% of all items at Pony Express','Pony Express is the place to get your new threads, and now you can them at a discounted rate just for you!\r\n\r\nSay the word FAMOUS when buying and you can get a 10% discount on all items!!',NULL,'Valid until further notice.','Pony Express',NULL,NULL,NULL,NULL,NULL,NULL,51.2362379,-0.5776219,NULL,'clothes','/images/companylogos/pony-express-150x150.jpg','0','0');
INSERT INTO "posts" VALUES(23,'2010-11-09 10:07:48','2011-03-22 00:28:33','Free Diagnostic at PC Repair Centre','PC Repairs is your one stop shop for all things technical, whether you need a new laptop, desktop, camera. OR need one fixed PC Repairs can help you! And now when you show your NUS card, PC Repairs will offer a free diagnostic. So if your PC is running like it should, go and see what''''s wrong with it, for free!',NULL,'Valid until further notice.','PC Repair Centre','','','','','','',51.237568,-0.5732415,'','PC repair diagnostic','/images/companylogos/PC-REPAIR-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(24,'2010-11-09 10:12:40','2010-11-09 10:12:40','3 for 2 on selected books at Waterstones','Waterstones in the centre of Guildford is offering 3 for 2 on selected books. Perfect for Christmas presents - or just for yourself!',NULL,'In store offers.','Waterstones',NULL,NULL,NULL,NULL,NULL,NULL,51.2362523,-0.5746837,NULL,'books novels','/images/companylogos/waterstones-150x150.jpg','0','0');
INSERT INTO "posts" VALUES(25,'2010-11-09 10:42:25','2011-03-22 00:28:10','15% discount at Crabtree & Evelyn','Crabtree &amp; Evelyn would be pleased to offer a 15% discount for NUS student card holders!\r\n\r\n(Terms and Conditions: Not valid in conjunction with any other offers)',NULL,'Valid until further notice.','Crabtree & Evelyn','','','','','','',51.2360398,-0.572088,'','','/images/companylogos/crab-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(26,'2010-11-09 12:38:28','2011-03-22 00:27:55','20% Off Hair Cuts at Saks Hair','Saks Hair are pleased to announce a 20% discount for all Guildford Students with an NUS card!!',NULL,'Valid until further notice.','Saks Hair','','','','','','',51.2349401,-0.5733539,'','hair cut hairdressers barber','/images/companylogos/saks-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(27,'2010-11-12 16:14:50','2011-03-22 00:27:36','20% Off Hair Cut At Martin "G"','Martin "G" is pleased to offer 20% off  gentlemen''''s hair cuts with an NUS Card! OR 10% without an NUS card if you print this voucher!\r\n\r\nOffer applies: Tuesday, Wednesday, Thursday and Friday.',NULL,'Valid until further notice.','Martin "G"','','','','','','',51.2447542,-0.5755933,'','hair cut hairdressers barber','/images/companylogos/MartinG-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(28,'2010-11-16 10:27:45','2010-11-16 10:27:50','Free Wine Tasting Lesson from Nicolas','Learn how to taste wine like a pro with our free 15 minute wine school. Free on tuesdays from now until 14th December from 3pm to 7pm. Simply call the store to book a place 01483 538032. Max group is 6 at a time. Not available on a Tuesday? Call anyway, we may be able to arrange another time.','2010-12-14','Tuesdays 3pm to 7pm.','Nicolas','(01483)538032',NULL,NULL,NULL,NULL,NULL,51.2372712,-0.5677017,NULL,'wine tasting','/images/companylogos/nicolas-1-150x150.jpg','0','0');
INSERT INTO "posts" VALUES(29,'2010-11-16 13:25:11','2011-04-18 17:16:29.203000','£5 Skate and Bowl! At Guildford Spectrum','Guildford Spectrum have an amazing offer for Guildford Students!\r\n\r\n£5 for a Bowl AND Skate! That means for just £5 you can go bowling and skating inclusive of shoe hire! You can do this on either a Tuesday or Thursday night! Just remember to print the voucher!

<a href="/docs/Bowl & Skate Combo Voucher 2010.pdf">Please download and print this voucher!!</a>

See you there!',NULL,'Valid until further notice.','Guildford Spectrum','','','','','','',51.2476341,-0.563135,'','skate bowl bowling skating','/images/companylogos/spectrum-150x150.jpg','0','0');
INSERT INTO "posts" VALUES(30,'2010-11-16 14:48:18','2010-11-18 13:02:53','Boileroom Loyalty Card','The Boileroom Loyalty Card costs just £3 and entitles you to great drinks deals such as pints of Fosters for £3, Double vodka and energy drink for £3 and a bottle of Desperado for £3.50. Keep an eye out for monthly drinks specials as well! By being a member you also get great discounts on various events at The Boileroom and also Priority Tickets up to 28 hours before general release. If you''''ve ever thought about hiring the venue for your own private party, works Christmas do or want to put on your own gig then the loyalty card also gives you great discounts on hire fees.\r\n\r\nLike our noodles? The loyalty card will also give you a £2 discount on all our rice and noodle dishes, both during lunchtime between 12 - 4pm. Just show your card at The Bar.',NULL,'Valid until further notice.','Boileroom',NULL,NULL,NULL,NULL,NULL,NULL,51.2404669,-0.5723234,NULL,'drinks food bar','/images/companylogos/Boileroom-150x150.jpg','0','0');
INSERT INTO "posts" VALUES(31,'2010-11-19 09:26:48','2010-11-19 09:26:48','20 students tickets available - Woodshed Jazz Surrey','Legendary Afro rock band Osibas''''s Gregg Kofi Brown will be performing at the Guildford Cathedral Refectory with his 7 piece world-class band. They will be serving up a menu of Afro Rock, World music and funk. Special student discount -ticket only £5 from Guildford Tourist Information Office, 14 Tunsgate, tomorrow or at the door. Doors open 8pm. Only 20 students tickets available, must bring student ID! Tel: 01483 444333 for info.','','LIMITED TIME OFFER!!!','Woodshed Jazz Surrey','(01483)444333',NULL,NULL,NULL,NULL,NULL,51.3343272346403,-0.468083612442018,NULL,'tickets jazz rock band','/images/companylogos/woodshedjazz-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(32,'2010-11-26 19:29:45','2010-11-26 19:49:51','Sally Beauty Supplies - Free Miracle 10 Haircare Sachet!!','<strong>Miracle 10 </strong>is an amazing new hair care product that does 10 things instantly\r\n\r\n1.Repairs dry damaged hair\r\n2.Adds shine\r\n3.Smoothes &amp; controls frizz\r\n4.Seals &amp; protects hair colour\r\n5.Detangles\r\n6.Prevents split ends\r\n7.Stops hair breakage\r\n8.Creates Silkiness\r\n9.Enhances natural body\r\n10.Flat iron spray &amp; thermal protector\r\n\r\nEasy to use: Shampoo and condition hair, towel dry, and comb product through. Blow dry or style as desired.\r\n\r\n<strong>Miracle 10 is ...10 out of 10.</strong>\r\n\r\n<strong>But hurry – only while stocks last.</strong>\r\n\r\n<strong>1 Sachet per Person only!</strong>\r\n\r\n73 North Street, Guildford,\r\n\r\nPhone: 01483 453800\r\n\r\n<strong>(opposite Pizza Hut!)</strong>',NULL,'Valid while stocks last.','Sally Beauty Supplies','(01483)453800',NULL,NULL,NULL,NULL,'73 North Street,
Guildford',51.2368404,-0.5726731,NULL,'hair beauty','/images/companylogos/Sally-150x150.jpg','0','0');
INSERT INTO "posts" VALUES(33,'2010-11-26 19:37:42','2010-11-26 19:38:44','Fahrenheit 55 - Student Nights!','<p>Great nights be had at Fahrenheit!</p>\r\n<p>Monday student night kane fm''''s elegant soul dj set 10pm-2 am free entry selected beers/ vodka energy drink  £2.50 all night</p>\r\n<p>\r\nThursday 3 for 2 on all sharing platters and 1/3 of all cocktails/ selected beers £3 bottle @the lounge 7-10 then  free entry to fahrenheit and all standard shots £2.50 all night</p>',NULL,'Mondays and Thursdays','Fahrenheit 55',NULL,NULL,NULL,NULL,NULL,NULL,51.23488,-0.57145,NULL,'drink club bar','/images/companylogos/fahrenhite55-150x150.jpg','0','1');
INSERT INTO "posts" VALUES(34,'2010-12-22 16:04:16','2011-04-21 18:12:46.937000','Fresh Choices - 10% student discount anytime','Fresh Choices - great food freshly made. The coffee shop is open all day from 7.30am, and is located at 87 North Street (at the top of North Street, next door to the Post Office)\r\n\r\n10% Student Discount ANYTIME\r\n\r\nOffers are:All regular takeaway hot drinks 99p before 12\r\n\r\nFree regular hot drink with our famous Full English &amp; Veggie breakfasts\r\n\r\nAny cake &amp; regular hot drink £3.50 before 12\r\n\r\nTakeaway meal deal £3.50Soup &amp; sandwich from £5.50\r\n\r\nHalf price cake with any hot drink after 2.30\r\n\r\nFor students we will still apply a 10% discount even to offers!',NULL,'Valid until further notice.','Fresh Choices',NULL,NULL,NULL,NULL,NULL,'87 North Street',51.2369296,-0.5722621,NULL,'coffee food drink','/images/companylogos/Fresh-150x150.png','0','1');
INSERT INTO "posts" VALUES(35,'2011-03-19 21:38:16','2011-04-18 22:00:51.687000','15% off first order','Web Exclusive Offer

15 % of your first order at The Student Boutique 
http://www.thestudentboutique.co.uk/pages/clothes_86848.cfm

discount code ''''gimme15''''''',NULL,'Valid until further notice','The Student Boutique','(01617)231750','candice@thestudentboutique.co.uk','http://www.thestudentboutique.co.uk/pages/clothes_86848.cfm','http://www.facebook.com/group.php?gid=367743221340','http://twitter.com/CandiceTSBoutiq','',NULL,NULL,'','clothes','/images/companylogos/StudentBoutique150x150.png','1','0');
